import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { Observable, forkJoin } from 'rxjs';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';
import { UserService } from '../services/user';

interface ScheduleStage {
  stageId: number | null;
  no: number;
  programme: string;
  statutoryRequirement: string;
  actualProgramme: string | null;
  permissibleCutoffDate: string | null;
  remarks: string | null;
  isAutoGenerated: boolean;
  isHolidayAdjusted: boolean;
}

interface EditSnapshot {
  actualProgramme: string | null;
  permissibleCutoffDate: string | null;
  remarks: string | null;
}

interface Holiday {
  id: number;
  date: string;
  description: string;
}

// Placeholder reference text shown before any schedule has been
// generated yet — transcribed from the TNSCSEC "Check List for
// Programme Dates" form. Once a schedule exists on the backend, its
// own programme/statutory_requirement text (and real stage ids)
// replace this entirely.
const CHECKLIST: { no: number; programme: string; statutoryRequirement: string }[] = [
  { no: 1, programme: 'Publication of Election Notice by the District Election Officer', statutoryRequirement: '15 days prior to the date of poll (52(6)(a)&(b))' },
  { no: 2, programme: 'Furnishing the Members list to the Electoral Officer by the society', statutoryRequirement: '15 days prior to the date of poll (52(5)(b)(i)(A), 52(7)(c))' },
  { no: 3, programme: 'Publishing the Members list by the Society in the notice board at the Office of the Society', statutoryRequirement: '15 days prior to the date of poll (52(5)(b)(i)(A), 52(7)(c))' },
  { no: 4, programme: 'Publication of voters list by the Electoral Officer', statutoryRequirement: 'Not less than 10 clear days prior to date of poll (52(7)(f))' },
  { no: 5, programme: 'Publication of voters list by the Electoral Officer in case the list of members are not furnished by the society and he himself prepare the voters list', statutoryRequirement: '---' },
  { no: 6, programme: 'Filing Claims or objections to the Voters List', statutoryRequirement: 'Within 2 days of publication of voters list (52(5)(b)(i)(c), 52(7)(f))' },
  { no: 7, programme: 'Decision of the Electoral Officer on claims made or objections raised', statutoryRequirement: '---' },
  { no: 8, programme: 'Publication of final voters list by the Electoral Officer', statutoryRequirement: 'At least 2 days prior to the date fixed for filing of Nomination (52(5)(b)(i)(D), 52(7)(g))' },
  { no: 9, programme: 'Filing of Nomination', statutoryRequirement: 'Not less than 3 clear days between the date fixed for filing of nomination and the date of poll (52(5)(b)(iii)(A), 52(8)(b))' },
  { no: 10, programme: 'Scrutiny of Nominations', statutoryRequirement: 'Next day after the date fixed for filing of Nomination (52(5)(b)(iii)(B), 52(8)(d))' },
  { no: 11, programme: 'Publication of list of valid Nominations', statutoryRequirement: 'On the same day of the scrutiny (52(5)(b)(iii)(B), 52(8)(g))' },
  { no: 12, programme: 'Withdrawal of Nomination', statutoryRequirement: 'Next day of the scrutiny (52(5)(b)(iii)(C), 52(8)(h))' },
  { no: 13, programme: 'Publication of final list of contesting candidates', statutoryRequirement: '---' },
  { no: 14, programme: 'Polling if required', statutoryRequirement: 'Not less than 3 clear days between the date fixed for filing of Nomination and the date of poll (52(6)(a)(iv), 52(5)(b)(iii)(E) proviso, 52(9)(b), 52(9)(h))' },
  { no: 15, programme: 'Counting and Declaration of Results', statutoryRequirement: '---' },
  { no: 16, programme: 'Issue of notice for Election of Office Bearers', statutoryRequirement: 'As soon as the members of the board have been elected, notice for the meeting shall be given (53(21))' },
  { no: 17, programme: 'Election of President / Vice-President', statutoryRequirement: 'Not less than 3 clear days (53(3)(a))' }
];

@Component({
  selector: 'app-electionschedule',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './electionschedule.html',
  styleUrls: ['./electionschedule.css']
})
export class ElectionSchedule implements OnInit {

  // Anyone can view this page; only an admin can edit the fields.
  isAdmin = localStorage.getItem('role') === 'admin';

  // Single section on this page — locked until the admin clicks Edit,
  // "Submit" saves and locks it back (same pattern as Election
  // Programme).
  unlocked = false;

  // id of the election_schedule row on the backend. null until the
  // first successful Generate — after that, Polling Date's Submit
  // calls "regenerate" instead of "generate".
  scheduleId: number | null = null;

  // The date of poll — shown above the table with its own Submit,
  // which generates/regenerates every row's dates on the backend
  // (holiday-aware; manually-edited rows survive a regenerate).
  pollingDate: string | null = null;

  items: ScheduleStage[] = CHECKLIST.map(c => ({
    stageId: null,
    no: c.no,
    programme: c.programme,
    statutoryRequirement: c.statutoryRequirement,
    actualProgramme: null,
    permissibleCutoffDate: null,
    remarks: null,
    isAutoGenerated: false,
    isHolidayAdjusted: false
  }));

  // Snapshot of each row's editable fields, taken when Edit is
  // clicked — Submit diffs against this to know which rows actually
  // changed, and PATCHes only those (by their real stage id).
  private editSnapshot = new Map<number, EditSnapshot>();

  // ==========================================
  // GOVERNMENT HOLIDAYS — feed the backend's skip logic
  // ==========================================
  holidays: Holiday[] = [];
  newHolidayDate: string | null = null;
  newHolidayDescription = '';

  constructor(private userService: UserService) { }

  ngOnInit(): void {
    this.userService.getElectionSchedules().subscribe({
      next: (res: any) => {
        const rows: any[] = Array.isArray(res?.data) ? res.data : (res?.data ? [res.data] : []);
        const record = rows.filter((r: any) => r.is_active !== 0)[0]; // newest first, per the API
        if (record) this.applyRecord(record);
      },
      error: () => {
        // No schedule generated yet (or endpoint unreachable) — page
        // just shows the blank reference checklist.
      }
    });

    this.loadHolidays();
  }

  loadHolidays(): void {
    this.userService.getElectionScheduleHolidays().subscribe({
      next: (res: any) => {
        const rows: any[] = Array.isArray(res?.data) ? res.data : [];
        this.holidays = rows
          .filter((h: any) => h.is_active !== 0)
          .map((h: any) => ({
            id: h.id,
            date: this.toDateInput(h.holiday_date) || '',
            description: h.description
          }))
          .sort((a, b) => a.date.localeCompare(b.date));
      },
      error: () => {
        // No holidays yet, or endpoint unreachable — list stays empty.
      }
    });
  }

  addHoliday(): void {
    if (!this.isAdmin) return;

    if (!this.newHolidayDate || !this.newHolidayDescription.trim()) {
      alert('தேதி மற்றும் விவரத்தை உள்ளிடவும்');
      return;
    }

    this.userService.addElectionScheduleHoliday({
      holiday_date: this.newHolidayDate,
      description: this.newHolidayDescription.trim()
    }).subscribe({
      next: () => {
        this.newHolidayDate = null;
        this.newHolidayDescription = '';
        this.loadHolidays();
        this.notifyRegenerateIfNeeded();
      },
      error: (err: any) => alert(err?.error?.message || 'Holiday add failed')
    });
  }

  removeHoliday(holiday: Holiday): void {
    if (!this.isAdmin) return;
    if (!confirm(`"${holiday.description}" (${holiday.date}) விடுமுறையை நீக்கவா?`)) return;

    this.userService.deleteElectionScheduleHoliday(holiday.id).subscribe({
      next: () => {
        this.loadHolidays();
        this.notifyRegenerateIfNeeded();
      },
      error: (err: any) => alert(err?.error?.message || 'Holiday remove failed')
    });
  }

  // Adding/removing a holiday only affects FUTURE generate/regenerate
  // calls — an already-generated schedule doesn't update itself.
  private notifyRegenerateIfNeeded(): void {
    if (this.scheduleId) {
      alert(
        'விடுமுறை பட்டியல் புதுப்பிக்கப்பட்டது. ஏற்கனவே உருவாக்கப்பட்ட அட்டவணையில் இது தானாக பிரதிபலிக்காது — ' +
        'மேலே உள்ள Submit (Date of Poll) பொத்தானை மீண்டும் அழுத்தி Regenerate செய்யவும்.'
      );
    }
  }

  private toDateInput(iso: string | null | undefined): string | null {
    return iso ? String(iso).slice(0, 10) : null;
  }

  private applyRecord(record: any): void {

    this.scheduleId = record.id;
    this.pollingDate = this.toDateInput(record.poll_date);

    const stages: any[] = Array.isArray(record.election_schedule_stage)
      ? [...record.election_schedule_stage].sort((a, b) => a.sl_no - b.sl_no)
      : [];

    if (stages.length > 0) {
      this.items = stages.map((s: any) => ({
        stageId: s.id,
        no: s.sl_no,
        programme: s.programme,
        statutoryRequirement: s.statutory_requirement,
        actualProgramme: this.toDateInput(s.actual_date),
        permissibleCutoffDate: this.toDateInput(s.permissible_cutoff_date),
        remarks: s.remarks ?? null,
        isAutoGenerated: !!s.is_auto_generated,
        isHolidayAdjusted: !!s.is_holiday_adjusted
      }));
    }
  }

  startEdit(): void {
    if (!this.isAdmin || !this.scheduleId) return;

    this.editSnapshot.clear();
    this.items.forEach(item => {
      if (item.stageId != null) {
        this.editSnapshot.set(item.stageId, {
          actualProgramme: item.actualProgramme,
          permissibleCutoffDate: item.permissibleCutoffDate,
          remarks: item.remarks
        });
      }
    });

    this.unlocked = true;
  }

  submit(): void {
    if (!this.isAdmin || !this.scheduleId) return;

    const requests: Observable<any>[] = [];

    for (const item of this.items) {
      if (item.stageId == null) continue;

      const before = this.editSnapshot.get(item.stageId);
      if (!before) continue;

      const changes: any = {};
      if (item.actualProgramme !== before.actualProgramme) changes.actual_date = item.actualProgramme;
      if (item.permissibleCutoffDate !== before.permissibleCutoffDate) changes.permissible_cutoff_date = item.permissibleCutoffDate;
      if (item.remarks !== before.remarks) changes.remarks = item.remarks;

      if (Object.keys(changes).length > 0) {
        requests.push(this.userService.updateElectionScheduleStage(item.stageId, changes));
      }
    }

    if (requests.length === 0) {
      this.unlocked = false;
      alert('மாற்றங்கள் இல்லை (No changes to save)');
      return;
    }

    forkJoin(requests).subscribe({
      next: () => {
        this.unlocked = false;
        alert('சமர்ப்பிக்கப்பட்டது (Submitted successfully)');

        // Re-fetch so is_auto_generated / is_holiday_adjusted flags
        // reflect what the backend actually recorded after the edit.
        this.userService.getElectionSchedule(this.scheduleId!).subscribe({
          next: (res: any) => { if (res?.data) this.applyRecord(res.data); }
        });
      },
      error: (err: any) => alert(err?.error?.message || 'Submit failed')
    });
  }

  // Polling Date's own Submit — generates a brand-new schedule the
  // first time, or regenerates the existing one (preserving
  // manually-edited rows) on every call after that.
  generateDates(): void {

    if (!this.isAdmin) return;

    if (!this.pollingDate) {
      alert('வாக்குப்பதிவு தேதியை முதலில் தேர்வு செய்யவும்');
      return;
    }

    const payload = { poll_date: this.pollingDate };

    const request$ = this.scheduleId
      ? this.userService.regenerateElectionSchedule(this.scheduleId, payload)
      : this.userService.generateElectionSchedule(payload);

    request$.subscribe({
      next: (res: any) => {
        if (res?.data) this.applyRecord(res.data);
        alert(
          this.scheduleId
            ? 'அட்டவணை மீண்டும் உருவாக்கப்பட்டது (Regenerated)'
            : 'அட்டவணை உருவாக்கப்பட்டது (Generated)'
        );
      },
      error: (err: any) => alert(err?.error?.message || 'Generate failed')
    });
  }

  // Client-side export from whatever's currently loaded.
  download(): void {

    const rows = this.items.map(item => ({
      'Sl. No': item.no,
      'Programme': item.programme,
      'Statutory Requirement': item.statutoryRequirement,
      'Actual Programme': item.actualProgramme || '',
      'Permissible Cutoff Date': item.permissibleCutoffDate || '',
      'Remarks': item.remarks || '',
      'Auto Generated': item.isAutoGenerated ? 'Yes' : 'No',
      'Holiday Adjusted': item.isHolidayAdjusted ? 'Yes' : 'No'
    }));

    const sheet = XLSX.utils.json_to_sheet(rows);
    sheet['!cols'] = [
      { wch: 8 }, { wch: 55 }, { wch: 55 }, { wch: 18 }, { wch: 20 }, { wch: 30 }, { wch: 14 }, { wch: 16 }
    ];

    const workbook = XLSX.utils.book_new();
    XLSX.utils.sheet_add_aoa(sheet, [[`Date of Poll: ${this.pollingDate || '-'}`]], { origin: -1 });
    XLSX.utils.book_append_sheet(workbook, sheet, 'Election Schedule');

    const buffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });

    saveAs(
      new Blob([buffer], { type: 'application/octet-stream' }),
      'Election_Schedule.xlsx'
    );
  }
}
